### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SpeedSterKawaii** [gogo9211/Roblox-Remote-Spy#1]
Is this server sided? Can it grab the remotes that are being fired by other players?

**Comment by RexiRexii** [comment]
> Is this server sided? Can it grab the remotes that are being fired by other players?

bro this is like fe-disabler-tron 4000 it can do anything

**Comment by Mellonyt** [comment]
no its a rat it escapes lua vm and installs a rat onto ur pc and steals ur discord token

**Comment by gogo9211** [comment]
All of the above ^^

**Comment by SpeedSterKawaii** [comment]
WTF
